### PR TITLE
lint: fix linter warnings reported by golangci-lint

### LINKED ISSUE #519: Fix the latest linter errors
See warnings in this PR: https://github.com/sashabaranov/go-openai/pull/516/files

### PR DESCRIPTION
**Pull request by simonklee**
Fix linter warning reported by golangci-lint.

Fixes #519

### CODE REVIEW

**Comment by vvatanabe** [comment]
@sashabaranov Is there any reason why dot imports have been used until now? If there are no particularly critical issues, I think it would be okay to remove the non-recommended dot imports in this PR.

**Comment by sashabaranov** [comment]
@simonklee wow, I've underestimated the amount of changes needed to fix these issues. Thank you so much, you are the best! 🏅 


@vvatanabe I think it was used just for convenience, and it didn't cause any linter errors so far (seems like we've got a linter update 😅)

**Review by sashabaranov — APPROVED** [review]

**Comment by simonklee** [comment]
> @simonklee wow, I've underestimated the amount of changes needed to fix these issues. Thank you so much, you are the best! 🏅

No worries :)

**Comment by vvatanabe** [comment]
@simonklee This PR will make it easier to work on many other PRs! Thank you!

**Pull request merged**
