### PR TITLE
 It is possible to customize the settings for both AuthToken and BaseURL at the same time.

### PR DESCRIPTION
**Pull request by shengbox**
Please allow me to customize AuthToken and BaseURL at the same time

### CODE REVIEW

**Comment by sashabaranov** [comment]
@shengbox Hey, doesn't `DefaultAzureConfig(apiKey, baseURL, engine string)` fit your case?

https://pkg.go.dev/github.com/sashabaranov/go-openai#DefaultAzureConfig

**Comment by shengbox** [comment]
Due to the "Great Firewall" in China, Chinese users typically use a proxy server deployed on a VPS to access OpenAI.

**Comment by sashabaranov** [comment]
@shengbox so why doesn't `DefaultAzureConfig(apiKey, baseURL, engine string)` work for you? It sets both the `authToken` and `baseURL`

**Comment by shengbox** [comment]
@sashabaranov When I use DefaultAzureConfig, the APIType is set to AZURE, but actually what I need is APIType=OPEN_AI.

**Comment by sashabaranov** [comment]
@shengbox got it, what if you do something like:

```go
// set authToken and BaseURL
config := openai.DefaultConfig("your token")
config.BaseURL = "your base URL"

// create client
client := openai.NewClientWithConfig(config)
```

**Comment by shengbox** [comment]
Yes, that should work just fine.

**Pull request closed without merging**
