### PR TITLE
Support Tool Resources properties for Threads

### PR DESCRIPTION
**Pull request by pkosiec**
**Describe the change**

Support Tool Resources properties for Threads.

**Provide OpenAI documentation link**
- https://platform.openai.com/docs/api-reference/threads/createThread
- https://platform.openai.com/docs/api-reference/threads/modifyThread
- https://platform.openai.com/docs/api-reference/threads/object

**Describe your solution**
Describe how your changes address the problem or how they add the feature. This should include a brief description of your approach and any new libraries or dependencies you're using.

**Tests**
I've manually tested the functionality when using the library in the project I'm working on.

**Additional context**

Resolves https://github.com/sashabaranov/go-openai/issues/759

### CODE REVIEW

**Comment by temamagic** [comment]
@pkosiec Hello! Could you provide an example of how you use this? I tried to substitute a vector store in the request and am getting an error, would like to take a look at your version of using this

**Comment by pkosiec** [comment]
Hey @temamagic, this is how I used it:

```go
	return  i.openaiClient.CreateThread(ctx, openai.ThreadRequest{
		Metadata: map[string]any{
			// ...
		},
		ToolResources: openai.ToolResourcesRequest{
			FileSearch: &openai.FileSearchToolResourcesRequest{
				VectorStoreIDs: []string{
					"{customVectorStoreID}",
				},
			},
		},
		Messages: []openai.ThreadMessage{
			{
				Role:    openai.ThreadMessageRoleUser,
				Content: "prompt",
			},
		},
	})
```

Hope that helps!

**Review by sashabaranov — APPROVED** [review]
Thank you for the PR! I've added a minor comment — we either can add an additional field or just merge as is!

**Comment by pkosiec** [comment]
Thank you @sashabaranov, let me add the field ASAP 👍

**Comment by pkosiec** [comment]
@sashabaranov Done: https://github.com/sashabaranov/go-openai/pull/760/commits/9b434df1e88e06ddbe578698cd2fb47bf314dde3

**Review by sashabaranov — APPROVED** [review]

**Comment by temamagic** [comment]
> Hey @temamagic, this is how I used it:
> 
> ```go
> 	return  i.openaiClient.CreateThread(ctx, openai.ThreadRequest{
> 		Metadata: map[string]any{
> 			// ...
> 		},
> 		ToolResources: openai.ToolResourcesRequest{
> 			FileSearch: &openai.FileSearchToolResourcesRequest{
> 				VectorStoreIDs: []string{
> 					"{customVectorStoreID}",
> 				},
> 			},
> 		},
> 		Messages: []openai.ThreadMessage{
> 			{
> 				Role:    openai.ThreadMessageRoleUser,
> 				Content: "prompt",
> 			},
> 		},
> 	})
> ```
> 
> Hope that helps!

In my case, it helped to set the agents version to 2 after initializing the client, but thanks!

**Comment by pkosiec** [comment]
@temamagic Ah yes, forgot to mention that, sorry. Glad you figured it out!

**Pull request merged**
